image: ubuntu:latest

tasks:
  - before: |
      printf 'export PATH="%s:$PATH"\n' "~/.local/bin" >> $HOME/.bashrc && exit
  - init: |
      pip install pylint
  - command: |
      source ~/.bashrc
      clear
vscode:
  extensions:
    - ms-python.python
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
